### ISSUE TITLE
Module specifier "k6-junit" was tried to be loaded as remote module by prepending "https://" to it, which didn't work

### ISSUE THREAD

**Issue by poponuts** [simbadltd/k6-junit#6]
I get this error:
```
WARN[0000] The moduleSpecifier "k6-junit" has no scheme but we will try to resolve it as remote module. This will be deprecated in the future and all remote modules will need to explicitly use "https" as scheme. 
ERRO[0000] Module specifier "k6-junit" was tried to be loaded as remote module by prepending "https://" to it, which didn't work. If you are trying to import a nodejs module, this is not supported as k6 is _not_ nodejs based. Please read https://k6.io/docs/using-k6/modules for more information. Remote resolution error: "Get "https://k6-junit": dial tcp: lookup k6-junit: no such host"
        at go.k6.io/k6/js.(*InitContext).Require-fm (native)
        at file:///Users/poponuts/Repositories/k6/k6.config.ts:5:0(22)
        at go.k6.io/k6/js.(*InitContext).Require-fm (native)
        at file:///Users/poponuts/Repositories/k6/support/authenticate.ts:3:0(37)
        at go.k6.io/k6/js.(*InitContext).Require-fm (native)
        at file:///Users/poponuts/Repositories/k6/test/user.api.ts:4:0(46)  hint="script exception"
```

My `webpack.config.js` has:
```js
    externals: [
        function ({context, request}, c) {
            if (request.startsWith('k6') || request.startsWith('https://')) {
                return request === 'k6-junit' ? c() : c(null, 'commonjs ' + request);
            }
            return c();
        },
    ],
```

I created a `kg.config.ts` with the following:
```ts
import {jUnit} from "k6-junit";

export function handleSummary(data) {
    console.log('Preparing the end-of-test summary...');
    return {
        "./junit.xml": jUnit(data)
    };
}
```

Understandably, `package.json` has:
```json
{
  "devDependencies": {
    "k6-junit": "X.X.X"
  }
}
```

**Comment by simbadltd** [comment]
Hello. Please share the following:
1. k6 version
2. Full source code or reproduction steps

**Comment by poponuts** [comment]
k6 version 0.39.0

https://github.com/poponuts/k6-junit-boilerplate
run as per README: `k6 run -e ENVIRONMENT=test -e test/booking.api.ts`

**Comment by simbadltd** [comment]
@poponuts Thanks for the additional info. So, the root cause is that you're running k6 against TypeScript test. To make it work you need:
1. Run webpack to build plain js test files (like this: `webpack --stats-error-details`)
2. Run k6 against js test files (like this: `k6 run test.js`)

If u want I can publish an example.

**Comment by poponuts** [comment]
Sorry, if I understand you correctly, does this mean that your package can only work on `js` files and not `ts` files?
I tried to use this official k6 repo as a reference for typescript tests: https://github.com/grafana/k6-template-typescript and they work fine without the `k6-junit` package.

**Comment by simbadltd** [comment]
@poponuts It can work both ways, but it would be more correctly to transpile with webpack (see also [this](https://k6.io/docs/using-k6/modules/)). If it is mandatory to keep using ts without transpiling then u need to update ur exports:

From:
```ts
import {jUnit} from "k6-junit";
```

To:
```ts
import {jUnit} from "./node_modules/k6-junit/index.js";
```
