### ISSUE TITLE
please add to jslib - https://jslib.k6.io/

### ISSUE THREAD

**Issue by fenchu** [simbadltd/k6-junit#9]
I use this module because our ci gitlab-ci supports junit so I can see via gitlabs restapi which tests that fails.
this module works excellent, but I need node installed to install it, which bloats up the container.

I know I can craft it so I do not need node, but then I loose the flexibility of versioning control and updating.
So it would be great if it can be added to https://jslib.k6.io/.

Thanks
MortenB

**Comment by eshepelyuk** [comment]
k6 have announced support for regular EcmaScript modules soon,  so maybe this task is not required at all.

**Comment by simbadltd** [comment]
Hello @fenchu! While your idea is definetily great, k6 dev team won't accept community libs to theirs JSLib registry. Thus, it is not possible to resolve the issue, at least for now. As an example you can check the following PRs:
- https://github.com/grafana/jslib.k6.io/pull/95
- https://github.com/grafana/jslib.k6.io/pull/87

Сlosing it until better times.
